spring:
  application:
    name: husbcore-dev
  datasource:
    url: jdbc:postgresql://db:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      keepalive-time: 0
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/dev-data
    schemas: public
    url: jdbc:postgresql://db:5432/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

cookie:
  secure: false
