spring:
  flyway:
    enabled: true
    locations:
      - classpath:db/migration
    schemas: public
    url: ${FLYWAY_DB_URL}
    user: ${FLYWAY_DB_USER}
    password: ${FLYWAY_DB_PASSWORD}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      keepalive-time: 0
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

cookie:
  secure: true

husbcore:
  cors:
    allowed-origins:
      - https://squash.leogouchon.com
      - https://www.squash.leogouchon.com
      - https://babyfoot.leogouchon.com
      - https://www.babyfoot.leogouchon.com
